require: rubocop-rails

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスにコメントを残さない
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable
  Exclude:
    - db/**/*
    - vendor/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - Gemfile
    - Gemfile.lock
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - test/application_system_test_case.rb
