require: rubocop-rails

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

LineLength:
  Max: 120

FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - db/**/*
    - vendor/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - Gemfile
    - Gemfile.lock
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - test/application_system_test_case.rb
